<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Don't access directly
};

/**
 * The list of predefined languages
 *
 * for each language:
 * [code]   => ISO 639-1 language code
 * [locale] => WordPress locale
 * [name]   => name
 * [dir]    => text direction
 * [flag]   => flag code
 */
$languages = array(
	'af' => array(
		'code'   => 'af',
		'locale' => 'af',
		'name'   => 'Afrikaans',
		'dir'    => 'ltr',
		'flag'   => 'za',
	),
	'ar' => array(
		'code'   => 'ar',
		'locale' => 'ar',
		'name'   => 'العربية',
		'dir'    => 'rtl',
		'flag'   => 'arab',
	),
	'ary' => array(
		'code'   => 'ar',
		'locale' => 'ary',
		'name'   => 'العربية المغربية',
		'dir'    => 'rtl',
		'flag'   => 'ma',
	),
	'as' => array(
		'code'   => 'as',
		'locale' => 'as',
		'name'   => 'অসমীয়া',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'az' => array(
		'code'   => 'az',
		'locale' => 'az',
		'name'   => 'Azərbaycan',
		'dir'    => 'ltr',
		'flag'   => 'az',
	),
	'azb' => array(
		'code'   => 'az',
		'locale' => 'azb',
		'name'   => 'گؤنئی آذربایجان',
		'dir'    => 'rtl',
		'flag'   => 'az',
	),
	'bel' => array(
		'code'   => 'be',
		'locale' => 'bel',
		'name'   => 'Беларуская мова',
		'dir'    => 'ltr',
		'flag'   => 'by',
	),
	'bg_BG' => array(
		'code'   => 'bg',
		'locale' => 'bg_BG',
		'name'   => 'български',
		'dir'    => 'ltr',
		'flag'   => 'bg',
	),
	'bn_BD' => array(
		'code'   => 'bn',
		'locale' => 'bn_BD',
		'name'   => 'বাংলা',
		'dir'    => 'ltr',
		'flag'   => 'bd',
	),
	'bo' => array(
		'code'   => 'bo',
		'locale' => 'bo',
		'name'   => 'བོད་ཡིག',
		'dir'    => 'ltr',
		'flag'   => 'tibet',
	),
	'bs_BA' => array(
		'code'   => 'bs',
		'locale' => 'bs_BA',
		'name'   => 'Bosanski',
		'dir'    => 'ltr',
		'flag'   => 'ba',
	),
	'ca' => array(
		'code'   => 'ca',
		'locale' => 'ca',
		'name'   => 'Català',
		'dir'    => 'ltr',
		'flag'   => 'catalonia',
	),
	'ceb' => array(
		'code'   => 'ceb',
		'locale' => 'ceb',
		'name'   => 'Cebuano',
		'dir'    => 'ltr',
		'flag'   => 'ph',
	),
	'cs_CZ' => array(
		'code'   => 'cs',
		'locale' => 'cs_CZ',
		'name'   => 'Čeština',
		'dir'    => 'ltr',
		'flag'   => 'cz',
	),
	'cy' => array(
		'code'   => 'cy',
		'locale' => 'cy',
		'name'   => 'Cymraeg',
		'dir'    => 'ltr',
		'flag'   => 'wales',
	),
	'da_DK' => array(
		'code'   => 'da',
		'locale' => 'da_DK',
		'name'   => 'Dansk',
		'dir'    => 'ltr',
		'flag'   => 'dk',
	),
	'de_CH' => array(
		'code'   => 'de',
		'locale' => 'de_CH',
		'name'   => 'Deutsch',
		'dir'    => 'ltr',
		'flag'   => 'ch',
	),
	'de_CH_informal' => array(
		'code'   => 'de',
		'locale' => 'de_CH_informal',
		'name'   => 'Deutsch',
		'dir'    => 'ltr',
		'flag'   => 'ch',
	),
	'de_DE' => array(
		'code'   => 'de',
		'locale' => 'de_DE',
		'name'   => 'Deutsch',
		'dir'    => 'ltr',
		'flag'   => 'de',
	),
	'de_DE_formal' => array(
		'code'   => 'de',
		'locale' => 'de_DE_formal',
		'name'   => 'Deutsch',
		'dir'    => 'ltr',
		'flag'   => 'de',
	),
	'dzo' => array(
		'code'   => 'dz',
		'locale' => 'dzo',
		'name'   => 'རྫོང་ཁ',
		'dir'    => 'ltr',
		'flag'   => 'bt',
	),
	'el' => array(
		'code'   => 'el',
		'locale' => 'el',
		'name'   => 'Ελληνικά',
		'dir'    => 'ltr',
		'flag'   => 'gr',
	),
	'en_AU' => array(
		'code'   => 'en',
		'locale' => 'en_AU',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'au',
	),
	'en_CA' => array(
		'code'   => 'en',
		'locale' => 'en_CA',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'ca',
	),
	'en_GB' => array(
		'code'   => 'en',
		'locale' => 'en_GB',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'gb',
	),
	'en_NZ' => array(
		'code'   => 'en',
		'locale' => 'en_NZ',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'nz',
	),
	'en_US' => array(
		'code'   => 'en',
		'locale' => 'en_US',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'us',
	),
	'en_ZA' => array(
		'code'   => 'en',
		'locale' => 'en_ZA',
		'name'   => 'English',
		'dir'    => 'ltr',
		'flag'   => 'za',
	),
	'eo' => array(
		'code'   => 'eo',
		'locale' => 'eo',
		'name'   => 'Esperanto',
		'dir'    => 'ltr',
		'flag'   => 'esperanto',
	),
	'es_AR' => array(
		'code'   => 'es',
		'locale' => 'es_AR',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'ar',
	),
	'es_CL' => array(
		'code'   => 'es',
		'locale' => 'es_CL',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'cl',
	),
	'es_CO' => array(
		'code'   => 'es',
		'locale' => 'es_CO',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'co',
	),
	'es_ES' => array(
		'code'   => 'es',
		'locale' => 'es_ES',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'es',
	),
	'es_GT' => array(
		'code'   => 'es',
		'locale' => 'es_GT',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'gt',
	),
	'es_MX' => array(
		'code'   => 'es',
		'locale' => 'es_MX',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'mx',
	),
	'es_PE' => array(
		'code'   => 'es',
		'locale' => 'es_PE',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 'pe',
	),
	'es_VE' => array(
		'code'   => 'es',
		'locale' => 'es_VE',
		'name'   => 'Español',
		'dir'    => 'ltr',
		'flag'   => 've',
	),
	'et' => array(
		'code'   => 'et',
		'locale' => 'et',
		'name'   => 'Eesti',
		'dir'    => 'ltr',
		'flag'   => 'ee',
	),
	'eu' => array(
		'code'   => 'eu',
		'locale' => 'eu',
		'name'   => 'Euskara',
		'dir'    => 'ltr',
		'flag'   => 'basque',
	),
	'fa_AF' => array(
		'code'   => 'fa',
		'locale' => 'fa_AF',
		'name'   => 'فارسی',
		'dir'    => 'rtl',
		'flag'   => 'af',
	),
	'fa_IR' => array(
		'code'   => 'fa',
		'locale' => 'fa_IR',
		'name'   => 'فارسی',
		'dir'    => 'rtl',
		'flag'   => 'ir',
	),
	'fi' => array(
		'code'   => 'fi',
		'locale' => 'fi',
		'name'   => 'Suomi',
		'dir'    => 'ltr',
		'flag'   => 'fi',
	),
	'fo' => array(
		'code'   => 'fo',
		'locale' => 'fo',
		'name'   => 'Føroyskt',
		'dir'    => 'ltr',
		'flag'   => 'fo',
	),
	'fr_BE' => array(
		'code'   => 'fr',
		'locale' => 'fr_BE',
		'name'   => 'Français',
		'dir'    => 'ltr',
		'flag'   => 'be',
	),
	'fr_CA' => array(
		'code'   => 'fr',
		'locale' => 'fr_CA',
		'name'   => 'Français',
		'dir'    => 'ltr',
		'flag'   => 'quebec',
	),
	'fr_FR' => array(
		'code'   => 'fr',
		'locale' => 'fr_FR',
		'name'   => 'Français',
		'dir'    => 'ltr',
		'flag'   => 'fr',
	),
	'fy' => array(
		'code'   => 'fy',
		'locale' => 'fy',
		'name'   => 'Frysk',
		'dir'    => 'ltr',
		'flag'   => 'nl',
	),
	'gd' => array(
		'code'   => 'gd',
		'locale' => 'gd',
		'name'   => 'Gàidhlig',
		'dir'    => 'ltr',
		'flag'   => 'scotland',
	),
	'gl_ES' => array(
		'code'   => 'gl',
		'locale' => 'gl_ES',
		'name'   => 'Galego',
		'dir'    => 'ltr',
		'flag'   => 'galicia',
	),
	'gu' => array(
		'code'   => 'gu',
		'locale' => 'gu',
		'name'   => 'ગુજરાતી',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'haz' => array(
		'code'   => 'haz',
		'locale' => 'haz',
		'name'   => 'هزاره گی',
		'dir'    => 'rtl',
		'flag'   => 'af',
	),
	'he_IL' => array(
		'code'   => 'he',
		'locale' => 'he_IL',
		'name'   => 'עברית',
		'dir'    => 'rtl',
		'flag'   => 'il',
	),
	'hi_IN' => array(
		'code'   => 'hi',
		'locale' => 'hi_IN',
		'name'   => 'हिन्दी',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'hr' => array(
		'code'   => 'hr',
		'locale' => 'hr',
		'name'   => 'Hrvatski',
		'dir'    => 'ltr',
		'flag'   => 'hr',
	),
	'hu_HU' => array(
		'code'   => 'hu',
		'locale' => 'hu_HU',
		'name'   => 'Magyar',
		'dir'    => 'ltr',
		'flag'   => 'hu',
	),
	'hy' => array(
		'code'   => 'hy',
		'locale' => 'hy',
		'name'   => 'Հայերեն',
		'dir'    => 'ltr',
		'flag'   => 'am',
	),
	'id_ID' => array(
		'code'   => 'id',
		'locale' => 'id_ID',
		'name'   => 'Bahasa Indonesia',
		'dir'    => 'ltr',
		'flag'   => 'id',
	),
	'is_IS' => array(
		'code'   => 'is',
		'locale' => 'is_IS',
		'name'   => 'Íslenska',
		'dir'    => 'ltr',
		'flag'   => 'is',
	),
	'it_IT' => array(
		'code'   => 'it',
		'locale' => 'it_IT',
		'name'   => 'Italiano',
		'dir'    => 'ltr',
		'flag'   => 'it',
	),
	'ja' => array(
		'code'   => 'ja',
		'locale' => 'ja',
		'name'   => '日本語',
		'dir'    => 'ltr',
		'flag'   => 'jp',
	),
	'jv_ID' => array(
		'code'   => 'jv',
		'locale' => 'jv_ID',
		'name'   => 'Basa Jawa',
		'dir'    => 'ltr',
		'flag'   => 'id',
	),
	'ka_GE' => array(
		'code'   => 'ka',
		'locale' => 'ka_GE',
		'name'   => 'ქართული',
		'dir'    => 'ltr',
		'flag'   => 'ge',
	),
	'kab' => array(
		'code'   => 'kab',
		'locale' => 'kab',
		'name'   => 'Taqbaylit',
		'dir'    => 'ltr',
		'flag'   => 'dz',
	),
	'kk' => array(
		'code'   => 'kk',
		'locale' => 'kk',
		'name'   => 'Қазақ тілі',
		'dir'    => 'ltr',
		'flag'   => 'kz',
	),
	'km' => array(
		'code'   => 'km',
		'locale' => 'km',
		'name'   => 'ភាសាខ្មែរ',
		'dir'    => 'ltr',
		'flag'   => 'kh',
	),
	'ko_KR' => array(
		'code'   => 'ko',
		'locale' => 'ko_KR',
		'name'   => '한국어',
		'dir'    => 'ltr',
		'flag'   => 'kr',
	),
	'ckb' => array(
		'code'   => 'ku',
		'locale' => 'ckb',
		'name'   => 'کوردی',
		'dir'    => 'rtl',
		'flag'   => 'kurdistan',
	),
	'lo' => array(
		'code'   => 'lo',
		'locale' => 'lo',
		'name'   => 'ພາສາລາວ',
		'dir'    => 'ltr',
		'flag'   => 'la',
	),
	'lt_LT' => array(
		'code'   => 'lt',
		'locale' => 'lt_LT',
		'name'   => 'Lietuviškai',
		'dir'    => 'ltr',
		'flag'   => 'lt',
	),
	'lv' => array(
		'code'   => 'lv',
		'locale' => 'lv',
		'name'   => 'Latviešu valoda',
		'dir'    => 'ltr',
		'flag'   => 'lv',
	),
	'mk_MK' => array(
		'code'   => 'mk',
		'locale' => 'mk_MK',
		'name'   => 'македонски јазик',
		'dir'    => 'ltr',
		'flag'   => 'mk',
	),
	'ml_IN' => array(
		'code'   => 'ml',
		'locale' => 'ml_IN',
		'name'   => 'മലയാളം',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'mn' => array(
		'code'   => 'mn',
		'locale' => 'mn',
		'name'   => 'Монгол хэл',
		'dir'    => 'ltr',
		'flag'   => 'mn',
	),
	'mr' => array(
		'code'   => 'mr',
		'locale' => 'mr',
		'name'   => 'मराठी',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'ms_MY' => array(
		'code'   => 'ms',
		'locale' => 'ms_MY',
		'name'   => 'Bahasa Melayu',
		'dir'    => 'ltr',
		'flag'   => 'my',
	),
	'my_MM' => array(
		'code'   => 'my',
		'locale' => 'my_MM',
		'name'   => 'ဗမာစာ',
		'dir'    => 'ltr',
		'flag'   => 'mm',
	),
	'nb_NO' => array(
		'code'   => 'nb',
		'locale' => 'nb_NO',
		'name'   => 'Norsk Bokmål',
		'dir'    => 'ltr',
		'flag'   => 'no',
	),
	'ne_NP' => array(
		'code'   => 'ne',
		'locale' => 'ne_NP',
		'name'   => 'नेपाली',
		'dir'    => 'ltr',
		'flag'   => 'np',
	),
	'nl_BE' => array(
		'code'   => 'nl',
		'locale' => 'nl_BE',
		'name'   => 'Nederlands',
		'dir'    => 'ltr',
		'flag'   => 'be',
	),
	'nl_NL' => array(
		'code'   => 'nl',
		'locale' => 'nl_NL',
		'name'   => 'Nederlands',
		'dir'    => 'ltr',
		'flag'   => 'nl',
	),
	'nl_NL_formal' => array(
		'code'   => 'nl',
		'locale' => 'nl_NL_formal',
		'name'   => 'Nederlands',
		'dir'    => 'ltr',
		'flag'   => 'nl',
	),
	'nn_NO' => array(
		'code'   => 'nn',
		'locale' => 'nn_NO',
		'name'   => 'Norsk Nynorsk',
		'dir'    => 'ltr',
		'flag'   => 'no',
	),
	'oci' => array(
		'code'   => 'oc',
		'locale' => 'oci',
		'name'   => 'Occitan',
		'dir'    => 'ltr',
		'flag'   => 'occitania',
	),
	'pa_IN' => array(
		'code'   => 'pa',
		'locale' => 'pa_IN',
		'name'   => 'ਪੰਜਾਬੀ',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'pl_PL' => array(
		'code'   => 'pl',
		'locale' => 'pl_PL',
		'name'   => 'Polski',
		'dir'    => 'ltr',
		'flag'   => 'pl',
	),
	'ps' => array(
		'code'   => 'ps',
		'locale' => 'ps',
		'name'   => 'پښتو',
		'dir'    => 'rtl',
		'flag'   => 'af',
	),
	'pt_BR' => array(
		'code'   => 'pt',
		'locale' => 'pt_BR',
		'name'   => 'Português',
		'dir'    => 'ltr',
		'flag'   => 'br',
	),
	'pt_PT' => array(
		'code'   => 'pt',
		'locale' => 'pt_PT',
		'name'   => 'Português',
		'dir'    => 'ltr',
		'flag'   => 'pt',
	),
	'rhg' => array(
		'code'   => 'rhg',
		'locale' => 'rhg',
		'name'   => 'Ruáinga',
		'dir'    => 'ltr',
		'flag'   => 'mm',
	),
	'ro_RO' => array(
		'code'   => 'ro',
		'locale' => 'ro_RO',
		'name'   => 'Română',
		'dir'    => 'ltr',
		'flag'   => 'ro',
	),
	'ru_RU' => array(
		'code'   => 'ru',
		'locale' => 'ru_RU',
		'name'   => 'Русский',
		'dir'    => 'ltr',
		'flag'   => 'ru',
	),
	'sah' => array(
		'code'   => 'sah',
		'locale' => 'sah',
		'name'   => 'Сахалыы',
		'dir'    => 'ltr',
		'flag'   => 'ru',
	),
	'si_LK' => array(
		'code'   => 'si',
		'locale' => 'si_LK',
		'name'   => 'සිංහල',
		'dir'    => 'ltr',
		'flag'   => 'lk',
	),
	'sk_SK' => array(
		'code'   => 'sk',
		'locale' => 'sk_SK',
		'name'   => 'Slovenčina',
		'dir'    => 'ltr',
		'flag'   => 'sk',
	),
	'sl_SI' => array(
		'code'   => 'sl',
		'locale' => 'sl_SI',
		'name'   => 'Slovenščina',
		'dir'    => 'ltr',
		'flag'   => 'si',
	),
	'so_SO' => array(
		'code'   => 'so',
		'locale' => 'so_SO',
		'name'   => 'Af-Soomaali',
		'dir'    => 'ltr',
		'flag'   => 'so',
	),
	'sq' => array(
		'code'   => 'sq',
		'locale' => 'sq',
		'name'   => 'Shqip',
		'dir'    => 'ltr',
		'flag'   => 'al',
	),
	'sr_RS' => array(
		'code'   => 'sr',
		'locale' => 'sr_RS',
		'name'   => 'Српски језик',
		'dir'    => 'ltr',
		'flag'   => 'rs',
	),
	'su_ID' => array(
		'code'   => 'su',
		'locale' => 'su_ID',
		'name'   => 'Basa Sunda',
		'dir'    => 'ltr',
		'flag'   => 'id',
	),
	'sv_SE' => array(
		'code'   => 'sv',
		'locale' => 'sv_SE',
		'name'   => 'Svenska',
		'dir'    => 'ltr',
		'flag'   => 'se',
	),
	'szl' => array(
		'code'   => 'szl',
		'locale' => 'szl',
		'name'   => 'Ślōnskŏ gŏdka',
		'dir'    => 'ltr',
		'flag'   => 'pl',
	),
	'ta_IN' => array(
		'code'   => 'ta',
		'locale' => 'ta_IN',
		'name'   => 'தமிழ்',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'ta_LK' => array(
		'code'   => 'ta',
		'locale' => 'ta_LK',
		'name'   => 'தமிழ்',
		'dir'    => 'ltr',
		'flag'   => 'lk',
	),
	'tah' => array(
		'code'   => 'ty',
		'locale' => 'tah',
		'name'   => 'Reo Tahiti',
		'dir'    => 'ltr',
		'flag'   => 'pf',
	),
	'te' => array(
		'code'   => 'te',
		'locale' => 'te',
		'name'   => 'తెలుగు',
		'dir'    => 'ltr',
		'flag'   => 'in',
	),
	'th' => array(
		'code'   => 'th',
		'locale' => 'th',
		'name'   => 'ไทย',
		'dir'    => 'ltr',
		'flag'   => 'th',
	),
	'tl' => array(
		'code'   => 'tl',
		'locale' => 'tl',
		'name'   => 'Tagalog',
		'dir'    => 'ltr',
		'flag'   => 'ph',
	),
	'tr_TR' => array(
		'code'   => 'tr',
		'locale' => 'tr_TR',
		'name'   => 'Türkçe',
		'dir'    => 'ltr',
		'flag'   => 'tr',
	),
	'tt_RU' => array(
		'code'   => 'tt',
		'locale' => 'tt_RU',
		'name'   => 'Татар теле',
		'dir'    => 'ltr',
		'flag'   => 'ru',
	),
	'ug_CN' => array(
		'code'   => 'ug',
		'locale' => 'ug_CN',
		'name'   => 'Uyƣurqə',
		'dir'    => 'ltr',
		'flag'   => 'cn',
	),
	'uk' => array(
		'code'   => 'uk',
		'locale' => 'uk',
		'name'   => 'Українська',
		'dir'    => 'ltr',
		'flag'   => 'ua',
	),
	'ur' => array(
		'code'   => 'ur',
		'locale' => 'ur',
		'name'   => 'اردو',
		'dir'    => 'rtl',
		'flag'   => 'pk',
	),
	'uz_UZ' => array(
		'code'   => 'uz',
		'locale' => 'uz_UZ',
		'name'   => 'Oʻzbek',
		'dir'    => 'ltr',
		'flag'   => 'uz',
	),
	'vec' => array(
		'code'   => 'vec',
		'locale' => 'vec',
		'name'   => 'Vèneto',
		'dir'    => 'ltr',
		'flag'   => 'veneto',
	),
	'vi' => array(
		'code'   => 'vi',
		'locale' => 'vi',
		'name'   => 'Tiếng Việt',
		'dir'    => 'ltr',
		'flag'   => 'vn',
	),
	'zh_CN' => array(
		'code'   => 'zh',
		'locale' => 'zh_CN',
		'name'   => '中文 (中国)',
		'dir'    => 'ltr',
		'flag'   => 'cn',
	),
	'zh_HK' => array(
		'code'   => 'zh',
		'locale' => 'zh_HK',
		'name'   => '中文 (香港)',
		'dir'    => 'ltr',
		'flag'   => 'hk',
	),
	'zh_TW' => array(
		'code'   => 'zh',
		'locale' => 'zh_TW',
		'name'   => '中文 (台灣)',
		'dir'    => 'ltr',
		'flag'   => 'tw',
	),
);

/**
 * Filter the list of predefined languages
 *
 * @since 1.7.10
 *
 * @param array $languages
 */
$languages = apply_filters( 'pll_predefined_languages', $languages );
