name: 'Run PHPUnit and Behat tests'

description: 'Sets up PHP and its dependencies, installs WordPress test library along with plugins and themes then runs PHPUnit and Behat tests.'

inputs:
  php-version:
    description: 'PHP version to use.'
    required: true
    type: string
  wordpress-version:
    description: 'WordPress version to use. Accepts a numeric string of the version, "nightly", or "latest".'
    required: true
    type: string
  allow-failure:
    description: 'Whether or not the job is allowed to fail. Defaults to false.'
    required: false
    type: boolean
    default: false

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Set up PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php-version }}

    - name: Clean PHP Dependencies
      run: |
        if [[ ${{ inputs.wordpress-version }} == "5.8.x" ]]; then
          composer require --no-interaction --no-update --ignore-platform-reqs --dev "phpunit/phpunit ^7.5"
        fi
        composer remove --no-interaction --no-update --dev "phpstan/phpstan"
        composer remove --no-interaction --no-update --dev "wpsyntex/polylang-phpstan"
      shell: bash

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: 'highest'

    - name: Set up WordPress ${{ inputs.wordpress-version }} and WordPress Test Library
      uses: sjinks/setup-wordpress-test-library@master
      with:
        version: ${{ inputs.wordpress-version }}

    - name: Set up plugins and themes dependencies
      run: "bash tests/bin/install-plugins.sh"
      shell: bash

    - name: Run tests
      run: |
        vendor/bin/phpunit
        vendor/bin/behat
      shell: bash
