name: 'Run PHPUnit and Behat tests'

description: 'Set up PHP and its dependencies, install WordPress test library along plugins and themes then run PHPUnit and Behat tests.'

inputs:
    php-version:
        description: 'PHP version to use.'
        required: true
        type: string
    wordpress-version:
        description: 'WordPress version to use. Accept a numeric string of the version, "nightly" or "latest".'
        required: true
        type: string
    allow-failure:
        description: 'Whether or not the job is allowed to fail. Default to false.'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Set up PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php-version }}

    - name: Clean PHP Dependencies
      run: |
          if [[ ${{ inputs.wordpress-version }} == "5.8.x" ]]; then
            composer require --no-interaction --no-update --ignore-platform-reqs --dev "phpunit/phpunit ^7.5"
          fi
          composer remove --no-interaction --no-update --dev "phpstan/phpstan"
          composer remove --no-interaction --no-update --dev "wpsyntex/polylang-phpstan"
      shell: bash

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v2
      with:
       dependency-versions: 'highest'

    - name: Set up WordPress ${{ inputs.wordpress-version }} and WordPress Test Library
      uses: sjinks/setup-wordpress-test-library@master
      with:
        version: ${{ inputs.wordpress-version }}

    - name: Set up plugins and themes dependencies
      run: "bash tests/bin/install-plugins.sh"
      shell: bash

    - name: Run tests
      run: |
          vendor/bin/phpunit
          vendor/bin/behat
      shell: bash
