name: Coding Standards CI

on:
  push:
    branches: master
    paths:
      - '**.php'
      - '**.js'
      - 'phpcs.xml.dist'
      - 'phpstan.neon.dist'
      - 'phpstan-baseline.neon'
      - 'composer.json'
  pull_request:
    branches: master
    paths:
      - '**.php'
      - '**.js'
      - 'phpcs.xml.dist'
      - 'phpstan.neon.dist'
      - 'phpstan-baseline.neon'
      - 'composer.json'

jobs:
  testing:
    name: PHPCS and PHPStan with PHP 7.4

    runs-on: ubuntu-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: '7.4'

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: 'highest'

    - name: Run PHPCS
      run: vendor/bin/phpcs

    - name: Run PHPStan
      run: vendor/bin/phpstan analyze --memory-limit=1500M

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: ./.github/actions/notify
        with:
          is-success: ${{ job.status }}
