name: Integration and Unit Tests

on:
  push:
    branches: master
    paths:
      - '**.php'
      - 'phpunit.xml'
      - 'composer.json'
      - '**.yml'
      - '**.sh'
  pull_request:
    branches: master
    paths:
      - '**.php'
      - 'phpunit.xml'
      - 'composer.json'
      - '**.yml'
      - '**.sh'
  schedule:
    # Runs every Monday at 00:00.
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  testing:
    uses: polylang/.github/.github/workflows/reusable-integration-and-unit-tests.yml@main
